sudo: false

services:
  - docker

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - cmake

script:
  - make -j

env:
  - LANG="en_US.UTF-8"

os:
  - osx

